spring.application.name=husky-aiassistant-user
# ?????
spring.datasource.url=jdbc:mysql://localhost:3306/husky_aiassistant_user?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=147Husky369
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
